version: "3"
services:
  web:
    build:
      context: .
      dockerfile: pysrc/app/Dockerfile
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - redis
      - celery
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/database:/database
      - ~/.pubtrends/ssl:/ssl:ro
      - ~/.pubtrends/predefined:/predefined
      - ~/.pubtrends/search_results:/search_results
      - ~/.pubtrends/nltk-data:/home/user/nltk-data
      - ~/.pubtrends/gensim-data:/home/user/gensim-data
  celery:
    build:
      context: .
      dockerfile: pysrc/celery/Dockerfile
    depends_on:
      - redis
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/model:/model:ro
      - ~/.pubtrends/.cache:/home/user/.cache
      - ~/.pubtrends/predefined:/predefined
      - ~/.pubtrends/search_results:/search_results
      - ~/.pubtrends/nltk-data:/home/user/nltk-data
      - ~/.pubtrends/gensim-data:/home/user/gensim-data
  redis:
    image: redis:5.0
    volumes:
      - ~/.pubtrends/logs:/log
    # This command is used to process huge analysis results of 40k+ papers
    command: redis-server --timeout 0 --client-output-buffer-limit normal 0 0 0