version: "3"
services:
  web:
    build:
      context: .
      dockerfile: models/app/Dockerfile
      args:
      - PUBTRENDS_VERSION=0.1.development
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: models/celery/Dockerfile
      # TODO: change to real database URL
      args:
      - POSTGRESQL_URL=localhost
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=biolabs
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=pubtrends
    depends_on:
      - redis
  redis:
    image: redis