version: "3"
services:
  web:
    build:
      context: .
      dockerfile: pysrc/app/Dockerfile
    restart: always
    ports:
      - "443:4433"
    depends_on:
      - redis
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/database:/database
      - ~/.pubtrends/ssl:/ssl:ro
  worker:
    build:
      context: .
      dockerfile: pysrc/celery/Dockerfile
    depends_on:
      - redis
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
  redis:
    image: redis:5.0

