version: "3"
services:
  web:
    build:
      context: .
      dockerfile: pysrc/app/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - embeddings
      - celery
      - semantic
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/database:/database
      - ~/.pubtrends/results:/results

  celery:
    build:
      context: .
      dockerfile: pysrc/celery/Dockerfile
    depends_on:
      - redis
      - embeddings
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/results:/results
      - ~/.pubtrends/nltk_data:/home/user/nltk_data
      - ~/.pubtrends/gensim-data:/home/user/gensim-data
  redis:
    image: redis:7.4.2
    volumes:
      - ~/.pubtrends/logs:/log
    # This command is used to process huge analysis results of 40k+ papers
    command: redis-server --timeout 0 --client-output-buffer-limit normal 0 0 0
  embeddings:
    build:
      context: .
      dockerfile: pysrc/endpoints/embeddings/sentence_transformer/Dockerfile
    restart: always
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/sentence-transformers:/sentence-transformers
      - ~/.pubtrends/nltk_data:/home/user/nltk_data
  semantic:
    build:
      context: .
      dockerfile: pysrc/endpoints/semantic_search/Dockerfile
    restart: always
    depends_on:
      - embeddings
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/faiss:/faiss:ro