version: "3"
services:
  web:
    build:
      context: .
      dockerfile: pysrc/app/Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - fasttext
      - celery
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/database:/database
      - ~/.pubtrends/ssl:/ssl:ro
      - ~/.pubtrends/results:/results
      - ~/.pubtrends/nltk-data:/home/user/nltk-data
      - ~/.pubtrends/gensim-data:/home/user/gensim-data
  celery:
    build:
      context: .
      dockerfile: pysrc/celery/Dockerfile
    depends_on:
      - redis
      - fasttext
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/model:/model:ro
      - ~/.pubtrends/.cache:/home/user/.cache
      - ~/.pubtrends/results:/results
      - ~/.pubtrends/nltk-data:/home/user/nltk-data
      - ~/.pubtrends/gensim-data:/home/user/gensim-data
  redis:
    image: redis:7.4.2
    volumes:
      - ~/.pubtrends/logs:/log
    # This command is used to process huge analysis results of 40k+ papers
    command: redis-server --timeout 0 --client-output-buffer-limit normal 0 0 0
  fasttext:
    build:
      context: .
      dockerfile: pysrc/fasttext/Dockerfile
    restart: always
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/model:/model
      - ~/.pubtrends/nltk-data:/home/user/nltk-data
      - ~/.pubtrends/gensim-data:/home/user/gensim-data