version: "3"
services:
  web:
    build:
      context: .
      dockerfile: models/app/Dockerfile
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - redis
    volumes:
      - ./logs:/logs
  worker:
    build:
      context: .
      dockerfile: models/celery/Dockerfile
    depends_on:
      - redis
    volumes:
      - ./logs:/logs
  redis:
    image: redis

