version: "3"
services:
  web:
    build:
      context: .
      dockerfile: pysrc/app/Dockerfile
    restart: always
    ports:
      - "443:4433"
    depends_on:
      - redis
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/database:/database
      - ~/.pubtrends/ssl:/ssl:ro
      - ~/.pubtrends/predefined:/predefined
  worker:
    build:
      context: .
      dockerfile: pysrc/celery/Dockerfile
    deploy:
      resources:
        limits:
          memory: 6G
    depends_on:
      - redis
    volumes:
      - ~/.pubtrends:/config:ro
      - ~/.pubtrends/logs:/logs
      - ~/.pubtrends/model:/model:ro
      - ~/.pubtrends/.cache:/home/user/.cache
  redis:
    image: redis:5.0

