# Keep this file as small as possible! Only explicit imports here!
name: pubtrends
channels:
  - anaconda # Required for word2vec
  - conda-forge
  - bokeh
  - pytorch
dependencies:
  - biopython=1.79
  - bokeh=2.4.2
  - cachetools=4.2.2
  - celery=4.4.0
  - flask=2.0.3
  - flask-admin=1.5.8
  - flask-security=3.0.0
  - flask-sqlalchemy=2.5.1
  - ipywidgets=7.6.5
  - holoviews=1.14.8
  - gensim=4.2.0
  - matplotlib=3.5.2
  - more-itertools=8.12.0
  - networkx=2.7.1
  - nltk=3.7
  - pandas=1.4.3
  - parameterized=0.8.1
  - psutil=5.9.0
  - psycopg2=2.9.3
  - pytest=7.1.2
  - python-louvain=0.15
  - pytorch=1.10.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - spacy=3.3.1
  - statsmodels=0.13.2
  - sqlalchemy=1.4.32
  - sqlite=3.38.5
  - tqdm=4.64.0
  - transformers=4.18.0
  - unidecode=1.2.0
  - wordcloud=1.8.2.2
  - pip
  - pip:
      - gunicorn==20.1.0
      - redis==3.5.3
      - vine==1.3.0
      - lazy==1.4
      - rouge==1.0.0
      - email-validator==1.1.3
      - text2num==2.4.0
      - python-Levenshtein==0.12.2 # Fix warning from gensim
      - teamcity-messages==1.29
      - pytest-flake8==1.0.7
