# Keep this file as small as possible! Only explicit imports here!
name: pubtrends
channels:
  - anaconda
  - conda-forge
  - bokeh
  - pytorch
dependencies:
  - bokeh=2.0.2
  - cachetools=3.1.1
  - celery=4.4.0
  - ipywidgets=7.5.1
  - holoviews=1.13.2
  - flask=1.1.2
  - matplotlib=3.2.1
  - nltk=3.4.4
  - pandas=1.0.3
  - parameterized=0.7.4
  - python=3.8.2
  - pytest=5.4.1
  - psycopg2=2.8.5
  - wordcloud=1.6.0
  - networkx=2.4
  - python-louvain=0.13
  - scikit-learn=0.22.1
  - pytorch=1.6.0
  - transformers=3.1.0
  - tensorboardx=2.1
  - psutil=5.7.2
  - unidecode=1.1.0
  - pip
  - pip:
      - gunicorn
      - redis
      - vine==1.3.0
      - lazy==1.4
      - rouge==1.0.0
      - neo4j==1.7.6
      - flask-admin==1.5.6
      - flask-security==3.0.0
      - flask-sqlalchemy==2.4.1
      - email-validator==1.1.0
