# Keep this file as small as possible! Only explicit imports here!
name: pubtrends
channels:
  - anaconda
  - conda-forge
  - bokeh
dependencies:
  - bokeh=1.3.4
  - biopython=1.73
  - celery=4.4.0rc1
  - ipywidgets=7.5.0
  - holoviews=1.12.3
  - flask=1.1.1
  - matplotlib=3.1.1
  - nltk=3.4.4
  - pandas=0.24.2
  - parameterized=0.6.1
  - psycopg2=2.7.6.1
  - python=3.7.3
  - pytest=5.0.1
  - wordcloud=1.5.0
  - networkx=2.3
  - python-louvain=0.13
  - scikit-learn=0.21.2