# Keep this file as small as possible! Only explicit imports here!
name: pubtrends
channels:
  - conda-forge
  - bokeh
  - pytorch
dependencies:
  - biopython=1.79
  - bokeh=3.6.3
  - cachetools=5.5.2
  - celery=5.4.0
  - flask=3.1.0
  - flask-admin=1.6.0
  - flask-caching=2.3.1
  - flask-security=5.6.0
  - flask-sqlalchemy=3.1.1
  - jinja2=3.1.6
  - ipywidgets=8.1.5
  - holoviews=1.20.1
  - huggingface_hub=0.29.1
  - gensim=4.3.3
  - matplotlib=3.10.1
  - more-itertools=10.6.0
  - networkx=3.4.2
  - nltk=3.9.1
  - pandas=2.2.3
  - parameterized=0.9.0
  - psutil=7.0.0
  - psycopg2=2.9.9
  - pytest=8.3.5
  - python=3.10.16
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - spacy=3.8.2
  - statsmodels=0.14.4
  - sqlalchemy=2.0.38
  - sqlite=3.49.1
  - tqdm=4.67.1
  - umap-learn=0.5.7
  - unidecode=1.3.8
  - wordcloud=1.9.4
  - pip
  - pip:
      - email-validator==2.2.0
      - gunicorn==23.0.0
      - redis==5.2.1
      - lazy==1.6
      - pytest-flake8==1.3.0
      - python-levenshtein==0.27.1 # Fix warning from gensim
      - rouge==1.0.1
      - teamcity-messages==1.33
      - text2num==2.5.1
      - vine==5.1.0
