name: pubtrends
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - amqp=2.5.0
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - backcall=0.1.0
  - beautifulsoup4=4.7.1
  - billiard=3.6.0.0
  - biopython=1.73
  - blas=1.0
  - bleach=3.1.0
  - bokeh=1.2.0
  - ca-certificates=2019.5.15
  - celery=4.4.0rc1
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.7
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - flask=1.0.3
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - holoviews=1.12.3
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.6.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - itsdangerous=1.1.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - kombu=4.6.1
  - krb5=1.16.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - nltk=3.4.3
  - notebook=5.7.8
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - param=1.9.1
  - parso=0.5.0
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - psycopg2=2.7.6.1
  - ptyprocess=0.6.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pysocks=1.7.0
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytest=5.0.1
  - pytz=2019.1
  - pyviz_comms=0.7.2
  - pyyaml=5.1.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.5.1
  - readline=7.0
  - requests=2.22.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - simplejson=3.16.0
  - sip=4.19.8
  - six=1.12.0
  - soupsieve=1.8
  - sqlalchemy=1.3.5
  - sqlite=3.28.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.2
  - urllib3=1.24.2
  - vine=1.3.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.4
  - wheel=0.33.4
  - widgetsnbextension=3.4.2
  - wordcloud=1.5.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - networkx==2.3
    - python-louvain==0.13
    - redis==3.2.1

