# Keep this file as small as possible! Only explicit imports here!
name: pubtrends
channels:
  - anaconda # Required for word2vec
  - conda-forge
  - bokeh
  - pytorch
dependencies:
  - biopython=1.79
  - bokeh=3.1.1
  - cachetools=4.2.2
  - celery=4.4.0
  - flask=2.2.2
  - flask-admin=1.6.0
  - flask-security=3.0.0
  - flask-sqlalchemy=3.0.2
  - jinja2=3.1.2
  - ipywidgets=8.0.4
  - holoviews=1.16.2
  - gensim=4.3.0
  - matplotlib=3.7.1
  - more-itertools=8.12.0
  - networkx=2.8.4
  - nltk=3.7
  - pandas=1.5.3
  - parameterized=0.8.1
  - psutil=5.9.0
  - psycopg2=2.9.3
  - pytest=7.3.1
  - python=3.10.12
  - python-louvain=0.15
  - pytorch=2.0.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - spacy=3.5.3
  - statsmodels=0.13.5
  - sqlalchemy=1.4.39
  - sqlite=3.41.2
  - tqdm=4.65.0
  - transformers=4.29.2
  - unidecode=1.2.0
  - wordcloud=1.9.2
  - pip
  - pip:
      - email-validator==1.2.1
      - gunicorn==20.1.0
      - redis==3.5.3
      - lazy==1.4
      - pytest-flake8==1.0.7
      - python-levenshtein==0.12.2 # Fix warning from gensim
      - rouge==1.0.0
      - teamcity-messages==1.29
      - text2num==2.4.0
      - vine==1.3.0
