# Keep this file as small as possible! Only explicit imports here!
name: pubtrends
channels:
  - anaconda # Required for word2vec
  - conda-forge
  - bokeh
  - stellargraph
  - pytorch
dependencies:
  - bokeh=2.3.2
  - cachetools=4.1.1
  - celery=4.4.0
  - flask=1.1.2
  - flask-admin=1.5.6
  - flask-security=3.0.0
  - flask-sqlalchemy=2.4.1
  - ipywidgets=7.5.1
  - holoviews=1.13.2
  - gensim=3.8.3
  - matplotlib=3.2.1
  - networkx=2.4
  - nltk=3.4.4
  - pandas=1.0.3
  - parameterized=0.7.4
  - psutil=5.7.2
  - psycopg2=2.8.5
  - pytest=5.4.1
  - python-louvain=0.13
  - pytorch=1.4.0
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.1
  - spacy=2.3.2
  - statsmodels=0.12.2
  - stellargraph=1.2.1
  - sqlalchemy=1.3.23
  - sqlite=3.33.0
  - tqdm=4.50.2
  - transformers=3.1.0
  - unidecode=1.1.0
  - wordcloud=1.6.0
  - pip
  - pip:
      - gunicorn
      - redis
      - vine==1.3.0
      - lazy==1.4
      - rouge==1.0.0
      - email-validator==1.1.0
      - text2num==2.2.1
      - teamcity-messages
      - pytest-flake8
