import gzip
import json
import os

from pysrc.papers.analyzer import KeyPaperAnalyzer
from pysrc.papers.db.loaders import Loaders
from pysrc.papers.pubtrends_config import PubtrendsConfig

FILE_DIR = os.path.abspath(os.path.dirname(__file__))
CLUSTERING_FOLDER = os.path.normpath(os.path.join(FILE_DIR, '../../clustering'))
PUBTRENDS_EXPORT_FOLDER = os.path.normpath(os.path.join(FILE_DIR, '../../pubtrends_export'))
PUBTRENDS_CONFIG = PubtrendsConfig(test=False)


def reload_exported_analyzer(path_to_archive, source='Pubmed'):
    """
    Load analysis data from json.gz archive generated by PubTrends.
    """
    with gzip.open(path_to_archive, 'rt', encoding='UTF-8') as zipfile:
        data = json.load(zipfile)

    loader, url_prefix = Loaders.get_loader_and_url_prefix(source, PUBTRENDS_CONFIG)
    analyzer = KeyPaperAnalyzer(loader, PUBTRENDS_CONFIG)
    analyzer.init(data)

    return analyzer


def get_review_pmids():
    return sorted([f.split('.')[0] for f in os.listdir(PUBTRENDS_EXPORT_FOLDER)])


def load_analyzer(pmid):
    analyzer_file = os.path.join(PUBTRENDS_EXPORT_FOLDER, f'{pmid}.json.gz')
    return reload_exported_analyzer(analyzer_file)


def load_clustering(pmid):
    clustering_file = os.path.join(CLUSTERING_FOLDER, f'{pmid}.json')
    with open(clustering_file, 'r') as f:
        clustering = json.load(f)
    return clustering
