\COPY (SELECT pmid, date, title, abstract, type, keywords, mesh, doi, aux from pmpublications) to 'pmpublications.tsv' WITH csv DELIMITER E'\t';
\COPY (SELECT pmid_out, pmid_in FROM pmcitations) to 'pmcitations.tsv' WITH csv DELIMITER E'\t';

# use tabs, because text may contain lots of commas
\COPY (SELECT ssid, pmid, title, abstract, year, doi, source, keywords, aux from sspublications) to 'sspublications.tsv' WITH csv DELIMITER E'\t';
\COPY (SELECT id_out, id_in FROM sscitations) to 'sscitations.tsv' WITH csv DELIMITER E'\t';